### ISSUE TITLE
Library[RS]: fix multinote bug

### ISSUE THREAD

**Issue by EvgenKor** [zkBob/libzkbob-rs#22]
The `libzkbob-rs` library works incorrect with some multinote transactions. If account has more than one consequential transactions which has more than 64 notes each, the receiving account cannot build correct transfer proof. Most likely here is a rust library problem. Need to discover and fix it

**Comment by ulyanas** [comment]
@EvgenKor  Please add notes for QA 

cc @vadimnikonov1
