### ISSUE TITLE
Move pool config to JS

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/libzkbob-rs#75]
For the simplicity of deploying a new pool, the hardcoded (pool: address_prefix) map should be removed from the libzkbob-rs library, moved to a higher level (zkbob-client-js), and made customizable from the application side. The Rust library should no longer have knowledge of address prefixes.

**Comment by EvgenKor** [comment]
PRs:
https://github.com/zkBob/libzkbob-rs/pull/77
https://github.com/zkBob/zkbob-client-js/pull/172
https://github.com/zkBob/zkbob-console/pull/100
